// <auto-generated />
namespace NWHarvest.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RenameFarmerGrower : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameFarmerGrower));
        
        string IMigrationMetadata.Id
        {
            get { return "201610151819559_RenameFarmerGrower"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
